/**
 * Значки режимов серверов — один набор на лаунчер и millida.net/katalog
 * (приказ владельца 30.09.2026: «перерисовать все иконки режимов с нуля в
 * стиле Blups»). Образец — плитки категорий Blups (`blups-redesign/webstore/
 * public/img/millida/cat-hosting.webp`): предмет 16×16 плоскими цветами с
 * одним бликом и одной тенью, толстый тёмный контур по силуэту, фон —
 * мозаика крупных клеток цвета режима со ступенчатым светом вокруг предмета.
 * Без градиентов и без эмодзи.
 *
 * Строка — ряд пикселей, буква — цвет из PAL, '.' — пусто. Контур
 * добавляется рендером (`render-mode-art.mjs`) по краю силуэта, поэтому
 * крайние ряды и колонки оставлены пустыми.
 */

export const PAL = {
  w: '#ffffff',
  W: '#d8dfea',
  g: '#9aa7ba',
  G: '#5f6b7e',
  x: '#34384a',
  r: '#ef3b3f',
  R: '#a81c2a',
  p: '#ff9cb0',
  o: '#ff8d1f',
  O: '#c45a00',
  y: '#ffd43b',
  Y: '#d99a00',
  l: '#72d64a',
  L: '#3b8f2a',
  e: '#b4f07f',
  b: '#43a7ff',
  B: '#1d5fc0',
  c: '#9aeaff',
  v: '#a468ff',
  V: '#6232b8',
  n: '#b0703c',
  N: '#6e4222',
  m: '#e0a86a',
  s: '#f3c787',
  S: '#c98e52',
  d: '#63f3e6',
  D: '#1fb0ab',
}

/** Цвет контура — почти чёрный с тёплым оттенком, как у Blups. */
export const OUTLINE = '#17131c'

/** @type {Record<string, { title: string; color: string; rows: string[] }>} */
export const MODE_ICONS = {
  // Меч по диагонали.
  PVP: {
    title: 'PvP',
    color: '#f07a18',
    rows: [
      '................',
      '...........www..',
      '..........wWWg..',
      '.........wWWg...',
      '........wWWg....',
      '.......wWWg.....',
      '......wWWg......',
      '..y..wWWg.......',
      '..yYwWWg........',
      '...yYWg.........',
      '...nYyY.........',
      '..nN.YyY........',
      '.yN....Y........',
      '.yy.............',
      '................',
      '................',
    ],
  },
  // Кирка: железная голова, деревянная рукоять.
  SURVIVAL: {
    title: 'Выживание',
    color: '#3aa83a',
    rows: [
      '................',
      '....wwwwww......',
      '...wWWWWWWg.....',
      '..wWggggggWg....',
      '..Wg....nNgWg...',
      '.......nN..gW...',
      '......nN....g...',
      '.....nN.........',
      '....nN..........',
      '...nN...........',
      '..nN............',
      '.nN.............',
      '.N..............',
      '................',
      '................',
      '................',
    ],
  },
  // Знак анархии: «A» в круге.
  ANARCHY: {
    title: 'Анархия',
    color: '#7a3fd0',
    rows: [
      '................',
      '.....rrrrrr.....',
      '...rrRRRRRRrr...',
      '..rRxxxwwxxxRr..',
      '..rxxxwwwwxxxr..',
      '.rRxxxwxxwxxxRr.',
      '.rxxxwwxxwwxxxr.',
      '.rxxxwxxxxwxxxr.',
      '.rxxwwwwwwwwxxr.',
      '.rxxwxxxxxxwxxr.',
      '..rxwwxxxxwwxr..',
      '..rRwxxxxxxwRr..',
      '...rrRRRRRRrr...',
      '.....rrrrrr.....',
      '................',
      '................',
    ],
  },
  // Театральная маска.
  RP: {
    title: 'RP',
    color: '#e8479a',
    rows: [
      '................',
      '..wwwwwwwwwwww..',
      '..wWWWWWWWWWWw..',
      '..wWWWWWWWWWWw..',
      '..wWxxWWWWxxWw..',
      '..wWxxxWWxxxWw..',
      '..wWWWWWWWWWWw..',
      '..wWWWWggWWWWw..',
      '...wWWWWWWWWw...',
      '...wWrWWWWrWw...',
      '....wWrrrrWw....',
      '....wWWRRWWw....',
      '.....wWWWWw.....',
      '......wwww......',
      '................',
      '................',
    ],
  },
  // Летающий остров с деревом.
  SKYBLOCK: {
    title: 'SkyBlock',
    color: '#2aa2e6',
    rows: [
      '................',
      '.......ll.......',
      '.....llelll.....',
      '....lleelLll....',
      '....llllllLl....',
      '.....lLlLLl.....',
      '.......nN.......',
      '.......nN.......',
      '..lelllnNlllll..',
      '..lllllllllllL..',
      '..nmnnnnnnnnnN..',
      '...nnNnnnnNnN...',
      '....nNnnnNnN....',
      '.....NnnNN......',
      '.......NN.......',
      '................',
    ],
  },
  // Сердце.
  LIFESTEAL: {
    title: 'LifeSteal',
    color: '#c81e4f',
    rows: [
      '................',
      '................',
      '..rrrr....rrrr..',
      '.rwwrrr..rrrrrr.',
      '.rwrrrrrrrrrrRr.',
      '.rrrrrrrrrrrrRr.',
      '.rrrrrrrrrrrRRr.',
      '..rrrrrrrrrrRr..',
      '...rrrrrrrrRr...',
      '....rrrrrrRr....',
      '.....rrrrRr.....',
      '......rrRr......',
      '.......rr.......',
      '................',
      '................',
      '................',
    ],
  },
  // Нагрудник.
  BOXPVP: {
    title: 'BoxPvP',
    color: '#2f62d8',
    rows: [
      '................',
      '..wwww....wwww..',
      '.wWWWWw..wWWWWw.',
      '.wWggWWwwWWggWw.',
      '.wWgWWWWWWWWgWw.',
      '..wWWWWWWWWWWw..',
      '...wWWWWWWWWw...',
      '...wWWWggWWWw...',
      '...wWWWWWWWWw...',
      '...wWWWWWWWWw...',
      '...wWggWWggWw...',
      '...wWWWWWWWWw...',
      '...wgggggggGw...',
      '....wwwwwwww....',
      '................',
      '................',
    ],
  },
  // Покебол.
  COBBLEMON: {
    title: 'Пиксельмон',
    color: '#d8403a',
    rows: [
      '................',
      '.....rrrrrr.....',
      '...rrwrrrrrrr...',
      '..rrwrrrrrrrRr..',
      '..rrrrrrrrrrRr..',
      '.rrrrrrrrrrrrRr.',
      '.rrrrrxxxxrrrRr.',
      '.xxxxxxwwxxxxxx.',
      '.WWWWWxwwxWWWWg.',
      '.WWWWWWxxWWWWWg.',
      '..WWWWWWWWWWWg..',
      '..WWWWWWWWWWgg..',
      '...WWWWWWWWgg...',
      '.....gggggg.....',
      '................',
      '................',
    ],
  },
  // Геймпад.
  MINIGAMES: {
    title: 'Мини-игры',
    color: '#eab308',
    rows: [
      '................',
      '................',
      '................',
      '...xxxxxxxxxx...',
      '..xGGGGGGGGGGx..',
      '.xGGwGGGGGGrGGx.',
      '.xGwwwGGGGbGrGx.',
      '.xGGwGGGGGGbGGx.',
      '.xGGGGGxxGGGGGx.',
      '.xGGGGx..xGGGGx.',
      '.xGGGx....xGGGx.',
      '..xxx......xxx..',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  // Кисть с краской.
  CREATIVE: {
    title: 'Креатив',
    color: '#13a98a',
    rows: [
      '................',
      '...........ll...',
      '..........lell..',
      '.........lelLl..',
      '........lllLl...',
      '........gWgl....',
      '.......gWg......',
      '......nNg.......',
      '.....nN.........',
      '....nN..........',
      '...nN...........',
      '..nN............',
      '.nN.............',
      '.N..............',
      '................',
      '................',
    ],
  },
  // Шестерня.
  TECHNICAL: {
    title: 'Техно',
    color: '#3b7ea6',
    rows: [
      '................',
      '......gggg......',
      '..gg..gWWg..gg..',
      '..gWggWWWWggWg..',
      '...gWWWWWWWWg...',
      '...gWWWggWWWg...',
      '.ggWWWg..gWWWgg.',
      '.gWWWg....gWWWg.',
      '.gWWWg....gWWWG.',
      '.ggWWWg..gWWWGG.',
      '...gWWWggWWWG...',
      '...gWWWWWWWWG...',
      '..gWGGWWWWGGWG..',
      '..gg..gWWG..GG..',
      '......GGGG......',
      '................',
    ],
  },
  // Травяной блок в изометрии — тот самый один блок.
  ONEBLOCK: {
    title: 'OneBlock',
    color: '#5fa832',
    rows: [
      '................',
      '.......ll.......',
      '.....lleell.....',
      '...lllelllell...',
      '.lllllllllllelL.',
      '.LLlllllllllLLn.',
      '.nLLLlllllLLLNN.',
      '.nnnLLLllLLLNNN.',
      '.nmnnnLLLNNNNnN.',
      '.nnnnmnnNNnNNNN.',
      '.nnmnnnnNNNNnNN.',
      '.nnnnnmnNnNNNNN.',
      '..nnnnnnNNNNNN..',
      '....nnnnNNNN....',
      '......nnNN......',
      '................',
    ],
  },
  // Ведро лавы.
  GRIEF: {
    title: 'Гриф',
    color: '#9a1f2a',
    rows: [
      '................',
      '....gggggggg....',
      '...g........g...',
      '..g..........g..',
      '..WWWWWWWWWWWW..',
      '..WoyoooooyooW..',
      '..WooooyooooOg..',
      '...WoOoooOoOg...',
      '...WWOOOOOOgg...',
      '...WWWWWWWWgg...',
      '....WWWWWWgg....',
      '....WWWWWWgg....',
      '.....gggggg.....',
      '................',
      '................',
      '................',
    ],
  },
  // Кровать.
  BEDWARS: {
    title: 'BedWars',
    color: '#d8262b',
    rows: [
      '................',
      '................',
      '................',
      '.nn.............',
      '.nnwwWW.........',
      '.nnwwWWrrrrrrrr.',
      '.nnWWWWrrrrrrrr.',
      '.nnrrrrrrrrrrrr.',
      '.nnRRRRRRRRRRRR.',
      '.nnnnnnnnnnnnnn.',
      '.NNNNNNNNNNNNNN.',
      '.NN..........NN.',
      '.NN..........NN.',
      '................',
      '................',
      '................',
    ],
  },
  // Остров с мечом: бой на островах в небе.
  SKYWARS: {
    title: 'SkyWars',
    color: '#16a9b5',
    rows: [
      '................',
      '.......ww.......',
      '.......wg.......',
      '.......wg.......',
      '.......wg.......',
      '.......wg.......',
      '.......wg.......',
      '.....yyYYyy.....',
      '.......nN.......',
      '..lelllnNlllll..',
      '..lllllllllllL..',
      '..nmnnnnnnnnnN..',
      '...nnNnnnnNnN...',
      '....nNnnnNnN....',
      '.....NnnNN......',
      '................',
    ],
  },
  // Сундук с припасами.
  HUNGER_GAMES: {
    title: 'Голодные игры',
    color: '#6b8f1f',
    rows: [
      '................',
      '................',
      '..nnnnnnnnnnnn..',
      '.nmmmmmmmmmmmmn.',
      '.nmnnnnnnnnnnmn.',
      '.nmnnnnnnnnnnmN.',
      '.NNNNNNggNNNNNN.',
      '.xxxxxxgWxxxxxx.',
      '.nmnnnnggnnnnmN.',
      '.nmnnnnnnnnnnmN.',
      '.nmnnnnnnnnnnmN.',
      '.nmmmmmmmmmmmmN.',
      '.NNNNNNNNNNNNNN.',
      '................',
      '................',
      '................',
    ],
  },
  // Щит.
  KITPVP: {
    title: 'KitPvP',
    color: '#b8471c',
    rows: [
      '................',
      '..gggggggggggg..',
      '..gnnnnWWnnnng..',
      '..gnmnnWWnnnNg..',
      '..gnnnnWWnnnNg..',
      '..gWWWWWWWWWWg..',
      '..gWWWWWWWWWWg..',
      '..gnnnnWWnnnNg..',
      '..gnmnnWWnnnNg..',
      '...gnnnWWnnNg...',
      '...gnnnWWnnNg...',
      '....gnnWWnNg....',
      '.....gnWWNg.....',
      '......gggg......',
      '................',
      '................',
    ],
  },
  // Знамя клана на древке.
  FACTIONS: {
    title: 'Кланы',
    color: '#4b4fd6',
    rows: [
      '................',
      '.yy.............',
      '.nN.bbbbbbbbbb..',
      '.nN.bcbbbbbbBb..',
      '.nN.bbbwwbbbBb..',
      '.nN.bbwwwwbbBb..',
      '.nN.bbbwwbbbBb..',
      '.nN.bbbbbbbbBb..',
      '.nN.bbbbbbbbBb..',
      '.nN.bbbBBbbbBb..',
      '.nN.bbB..BbbBb..',
      '.nN.bB....BbBb..',
      '.nN.B......BB...',
      '.nN.............',
      '.NN.............',
      '................',
    ],
  },
  // Решётка камеры.
  PRISON: {
    title: 'Тюрьма',
    color: '#56657a',
    rows: [
      '................',
      '.gggggggggggggg.',
      '.gWWWWWWWWWWWWG.',
      '.gGGGGGGGGGGGGG.',
      '..Wg.Wg.Wg.Wg...',
      '..Wg.Wg.Wg.Wg...',
      '..Wg.Wg.Wg.Wg...',
      '..Wg.Wg.WyyyY...',
      '..Wg.Wg.yY.yY...',
      '..Wg.Wg.yyyyY...',
      '..Wg.Wg.yYxyY...',
      '..Wg.Wg.YYYYY...',
      '.gggggggggggggg.',
      '.GGGGGGGGGGGGGG.',
      '................',
      '................',
    ],
  },
  // Домик.
  TOWNY: {
    title: 'Towny',
    color: '#b0673a',
    rows: [
      '................',
      '.......rr.......',
      '......rrrr......',
      '.....rrrrrr.....',
      '....rrrrrrrr....',
      '...rrrrrrrrrr...',
      '..RRRRRRRRRRRR..',
      '...mmmmmmmmmm...',
      '...mccmmmmccm...',
      '...mcbmmmmcbm...',
      '...mmmmnnmmmm...',
      '...mmmmnNmmmm...',
      '...mmmmnNmmmm...',
      '...SSSSNNSSSS...',
      '................',
      '................',
    ],
  },
  // Зелье.
  MMORPG: {
    title: 'РПГ',
    color: '#a53ad0',
    rows: [
      '................',
      '......nnnn......',
      '......NNNN......',
      '.......WW.......',
      '.......WW.......',
      '......W..W......',
      '.....W....W.....',
      '....WvvvvvvW....',
      '...WvwvvvvvvW...',
      '...WvwvvvvvVW...',
      '...WvvvvvvvVW...',
      '...WvvvvvvVVW...',
      '....WVVVVVVW....',
      '.....WWWWWW.....',
      '................',
      '................',
    ],
  },
  // Молоток.
  BUILD_BATTLE: {
    title: 'Build Battle',
    color: '#d9632e',
    rows: [
      '................',
      '....wwwwwww.....',
      '...wWWWWWWWg....',
      '...WWWWWWWWgG...',
      '...ggggggggGG...',
      '....GGGnNGGG....',
      '.......nN.......',
      '.......nN.......',
      '.......nN.......',
      '.......nN.......',
      '.......nN.......',
      '.......nN.......',
      '......xxxx......',
      '......xxxx......',
      '................',
      '................',
    ],
  },
  // Ботинок в прыжке.
  PARKOUR: {
    title: 'Паркур',
    color: '#72b81c',
    rows: [
      '................',
      '................',
      '.....bbbb.......',
      '.....bcbb.......',
      '.....bbbb.......',
      '.....bbbb.......',
      '.....bbbB.......',
      '.....bbbbbbb....',
      '.....bcbbbbbbb..',
      '.....bbbbbbbbBb.',
      '.....BBBBBBBBBB.',
      '.....WWWWWWWWWW.',
      '................',
      '.ww..ww.........',
      '................',
      '................',
    ],
  },
  // Лупа.
  HIDE_SEEK: {
    title: 'Прятки',
    color: '#3f8fd8',
    rows: [
      '................',
      '....gggggg......',
      '...gWWWWWWg.....',
      '..gWccbbbbWg....',
      '..gWcbbbbbWg....',
      '..gWbbbbbbWg....',
      '..gWbbbbbbWg....',
      '..gWbbbbbBWg....',
      '...gWWWWWWgn....',
      '....gggggg.Nn...',
      '............Nn..',
      '.............Nn.',
      '..............N.',
      '................',
      '................',
      '................',
    ],
  },
  // Нож.
  MURDER: {
    title: 'Murder Mystery',
    color: '#8e1f2c',
    rows: [
      '................',
      '.............w..',
      '............wW..',
      '...........wWg..',
      '..........wWg...',
      '.........wWg....',
      '........wWg.....',
      '.......wWg......',
      '......wWg.......',
      '.....GxG........',
      '....xrR.........',
      '...rRx..........',
      '..rR............',
      '..R.............',
      '................',
      '................',
    ],
  },
  // Лопата.
  SPLEEF: {
    title: 'Spleef',
    color: '#5fb3d9',
    rows: [
      '................',
      '..........www...',
      '.........wWWWg..',
      '.........WWWWg..',
      '.........WWWgG..',
      '........nNggG...',
      '.......nN.......',
      '......nN........',
      '.....nN.........',
      '....nN..........',
      '...nN...........',
      '..nN............',
      '.nN.............',
      '.N..............',
      '................',
      '................',
    ],
  },
  // Блок динамита.
  TNTRUN: {
    title: 'TNT Run',
    color: '#e24a2a',
    rows: [
      '................',
      '.......gg.......',
      '......g.........',
      '..rrrrrrrrrrrr..',
      '..rRrRrRrRrRrR..',
      '..rRrRrRrRrRrR..',
      '..wwwwwwwwwwww..',
      '..xxxwxwwxwxxx..',
      '..wxwwxxwxwwxw..',
      '..wxwwxwxxwwxw..',
      '..wxwwxwwxwwxw..',
      '..wwwwwwwwwwww..',
      '..rRrRrRrRrRrR..',
      '..RRRRRRRRRRRR..',
      '................',
      '................',
    ],
  },
  // Золотое яблоко.
  UHC: {
    title: 'UHC',
    color: '#c28a00',
    rows: [
      '................',
      '.......n........',
      '.......nll......',
      '.......Ll.......',
      '...yyyyNyyyy....',
      '..yywyyyyyyyY...',
      '..ywwyyyyyyyY...',
      '..yyyyyyyyyyY...',
      '..yyyyyyyyyYY...',
      '..yyyyyyyyyYY...',
      '...yyyyyyyYY....',
      '...yyyyyyYYY....',
      '....yYY.YYY.....',
      '................',
      '................',
      '................',
    ],
  },
  // Череп.
  HARDCORE: {
    title: 'Хардкор',
    color: '#3d2b5c',
    rows: [
      '................',
      '....wwwwwwww....',
      '...wWWWWWWWWw...',
      '..wWWWWWWWWWWw..',
      '..wWWWWWWWWWWg..',
      '..wWxxxWWxxxWg..',
      '..wWxxxWWxxxWg..',
      '..wWxxWWWWxxWg..',
      '..wWWWWxxWWWWg..',
      '...wWWWxxWWWg...',
      '....wWWWWWWg....',
      '....wWxWxWxg....',
      '....wWWWWWWg....',
      '.....gggggg.....',
      '................',
      '................',
    ],
  },
  // Глобус.
  EARTH: {
    title: 'Земля',
    color: '#2f7fc4',
    rows: [
      '................',
      '.....bbbbbb.....',
      '...bbcllbbbbb...',
      '..bclllllbbbbb..',
      '..blllllbbllbB..',
      '.bbllllbbllllBB.',
      '.bbbllbbbbllbBB.',
      '.bbbbbbbbbllbBB.',
      '.bbbbllbbbbbbBB.',
      '.bbbblllbbbbBBB.',
      '..bbblllbbbbBB..',
      '..bbbbllbbbBBB..',
      '...bbbbbbBBB....',
      '.....BBBBBB.....',
      '................',
      '................',
    ],
  },
  // Компас охотника.
  MANHUNT: {
    title: 'Манхант',
    color: '#8a3a1f',
    rows: [
      '................',
      '.....gggggg.....',
      '...ggWWWWWWgg...',
      '..gWWWWWWWWWWg..',
      '..gWWWWWWrrWWg..',
      '.gWWWWWWrrWWWWg.',
      '.gWWWWWrrWWWWWG.',
      '.gWWWWWxxWWWWWG.',
      '.gWWWWWxxWWWWWG.',
      '.gWWWWGGWWWWWWG.',
      '..gWWGGWWWWWWG..',
      '..gWWWWWWWWWWG..',
      '...ggWWWWWWGG...',
      '.....GGGGGG.....',
      '................',
      '................',
    ],
  },
  // Карточка бинго.
  BINGO: {
    title: 'Бинго',
    color: '#c79a12',
    rows: [
      '................',
      '..wwwwwwwwwwww..',
      '..wWWWWWWWWWWg..',
      '..wWrrWWWWbbWg..',
      '..wWrrWWWWbbWg..',
      '..wWWWWWWWWWWg..',
      '..wWWWWllWWWWg..',
      '..wWWWWllWWWWg..',
      '..wWWWWWWWWWWg..',
      '..wWyyWWWWrrWg..',
      '..wWyyWWWWrrWg..',
      '..wWWWWWWWWWWg..',
      '..wggggggggggg..',
      '................',
      '................',
      '................',
    ],
  },
  // Лаки-блок с вопросом.
  LUCKY: {
    title: 'Лаки-блоки',
    color: '#d99a00',
    rows: [
      '................',
      '..yyyyyyyyyyyy..',
      '..ywyyyyyyyyyY..',
      '..yyyywwwwyyyY..',
      '..yyywwYYwwyyY..',
      '..yyyYYyywwYyY..',
      '..yyyyyywwYYyY..',
      '..yyyyywwYyyyY..',
      '..yyyyywwYyyyY..',
      '..yyyyyYYyyyyY..',
      '..yyyyywwyyyyY..',
      '..yyyyyYYyyyyY..',
      '..yYYYYYYYYYYY..',
      '................',
      '................',
      '................',
    ],
  },
  // Лицо крипера — самая узнаваемая «ванилла».
  VANILLA: {
    title: 'Ванилла',
    color: '#2f9a55',
    rows: [
      '................',
      '..llllllllllll..',
      '..lellllllllLl..',
      '..llllllllllLl..',
      '..lxxxllllxxxl..',
      '..lxxxllllxxxl..',
      '..lllllxxlllLl..',
      '..llllxxxxllLl..',
      '..llllxxxxllLl..',
      '..llllxllxllLl..',
      '..llllllllllLl..',
      '..lLLLLLLLLLLl..',
      '..llllllllllll..',
      '................',
      '................',
      '................',
    ],
  },
}
